server:
  port: 15000
spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


  rabbitmq:
    host: 192.168.200.100
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-confirm-type: correlated   #发送端确认的方式：关联方式，错误的消息，必须通知publisher
    publisher-returns: true   #发送返回true，服务器只要收到消息了就通知发送方。
    listener:
      type: simple
      simple:
        acknowledge-mode: manual  #手动确认




app:
  threadpool:
    core-pool-size: 4
    maximum-pool-size: 8
    work-queue-size: 200
    keep-alive-time: 60
  alipay:
    app-id: 2016092200568607
    merchant-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDZgaoTCJNGbZ80iVrYJCK35XI75UeqRjeI8Jl/uNHna0eZZJv56f1GnRjna1GLhL9htl042EZ8R6LOJsD1W6Prf/MwdaX+PB8+3KpKfCI5GIK7lx+fJf6xi5MOAsJ7RT9kKq02joiS82o2xybZwxMS0KGuyOjxyskgFaoRv49jdOFsUCkQo7hidiaV57vFpbCeJXWCnwgXyw/QiEjip34Ps6W2FZH9eypYtnqzYQ25CrkKPkMst+xQA8WTseBkA/Y2YEFxYTf6cLJpsQWMMplQU5t/LnpRv4l9Et6jtwnxEuJvhGbk+2B1Ij0LV04+S1tNlBLLCgE/YmfvWUsEL9GdAgMBAAECggEAfpcf5EoGZWQh19Llg4yshDlPXhrYtfp+Ef5uaE6qJDVlC5rpyO9tkK6YMwBcCoatWHJqGU6O34BV+gPGJEc8xTDH2nlureRSDyUhG47Z4D8qv4F6TwcvECh64xmqFVK9TVAlVe5pAJYZSF5qdy05Kacxoued5DQxELJrND84dhoajeCjb9wvjVi9/5g48w+Mo9FLjmc/J1yspp73K8RHtQ0YoggTw9HkciofB9X+Mg8KOuODJuDnQgYVwLkBxw3O1gMn/Zlpp5zyBk6heq1XjqZ0/wGPpCBQeShnnnukbWiwq+1V14QJTfUmRxBp8EwWDfJeR3h6MiQHueJkkfIEgQKBgQD5Sq6EeUFZEeFnEC31URz0FSV2HOP4jn/ICX5AITpeTWALgQnyjNJ74a1E9eNeDZWtajPXdesn8MItlDmmX1zTGjbxhgG0z4y2WJqKoRWRYKzfafZfIU2YXWSRUxZqjdUruIN3e1Pt2pH0c7XC76oD2qurWHpJNfTWou5+T4VM/QKBgQDfXAVa11JEugLo51uN6IARLeCSTXaC84vb8nqpp3nrfK6Idf7Pz6gwlQUAHWtj5UajuvS1YLd6HZgwKFaNHuC5KYEKD2em3cU6Vcvvng1bncGmiRxvzC5Wui6wfig17Zzv6d7m/ZyfgtJZ0BPZYozQsYRyalI6xjye8Zhf/TwJIQKBgQDcU1b+mjRZRmZSsogL4s6WIwJi65HIohjpcQp2H2f45KXYRQnHpxJ4jrKW2kNDYvpAtDZxXTSirjTQF8sD8hCWOvsIZ4mmhjE1EAY2M7xeKnVfV8V5unNcEF7L2gVb01LuOztmJEe/Vofc509jpHI8yc0juSULA3cLJCFo3VtQ+QKBgQCgDL9ljZ9M0gFdxNLNCAokxTwDefBu+3d/fuw4f2KUxH4IGI0jeghp745qu6oFJfiNQF0zTv+KSISSFYWXj8W1yLDHdaxvXMCEAZClvhqSSKPH4r32uleGG9ly7KOBqSdonqvz100Q29xBMSHYBo8ix+FBX0BXD0/HERV/yuTnIQKBgA4O6ozUvi0x28nHefcQEN2YK3rK1CpWGQUOczzSqUWDNU8efjWMlbHg7RrnC2KUVU7n5UGN/iYXKfgK+gn4w7mt3ZbguDpigyQ5+S04RGWBlAn5YyckJwmOYqIRyccUtu6RDKtgGYwKNC3EbGnjY1nhmVlIfmCq2i+sLFdpq+gl
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyQQceVUChTJGtF/a8SXufhSxDTKporieTq9NO7yDZSpDlAX1zVPT/nf0KWAlxq1TYappWMIYtyrOABhJyn6flNP6vuSBiM5lYsepHvYrtRHqlFiJruEkiaCgEZBKL5aCfBHYj0oqgQn9MpNV/PEH4cBYAVaiI4+VX8CBUQfeEGjgN6OkpLULZ3X0JUkmSnVvCNJ1m3PD68IIlbOfEZXJUKCqmZhzprGR5VWswjxA+g87cMwvijL4gdkSy/daG62Bz5vApcmmMkuX1k1fMWP4ajZCASVw8HD+MSLRhd8We9F97gd8CW0TavzbdR+mTS5H4yEgO8F9HRAsbkhV9yu0yQIDAQAB
    notify-url: http://payment.gmall.com/payment/notify  #内网穿透  aaa.cccc.bbb/payment/notify
    return-url: http://payment.gmall.com/payment/success.html
    sign-type: RSA2
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do


