server:
  port: 12000

spring:
  datasource:
    url: jdbc:mysql://192.168.200.100:3306/gmall_user?useSSL=false&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
